# Generated by Django 5.1.8 on 2026-02-27 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_logcluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(blank=True, default='')),
                ('root_causes', models.JSONField(blank=True, default=list)),
                ('remediation', models.TextField(blank=True, default='')),
                ('runbook', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='analyses.analysisrun')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
