# Generated by Django 5.1.8 on 2026-02-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_aiinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='evidence_references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='overall_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
