# Generated by Django 5.1.8 on 2026-02-27 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('upload', 'Upload'), ('analyze_start', 'Analyze Start'), ('analyze_finish', 'Analyze Finish'), ('analyze_fail', 'Analyze Fail'), ('export', 'Export'), ('delete', 'Delete')], db_index=True, max_length=32)),
                ('source_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('analysis_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='audit_owner_created_idx'), models.Index(fields=['owner', 'event_type'], name='audit_owner_event_idx')],
            },
        ),
    ]
