# Generated by Django 5.1.8 on 2026-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogevent',
            name='event_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('analyze_start', 'Analyze Start'), ('analyze_finish', 'Analyze Finish'), ('analyze_fail', 'Analyze Fail'), ('export', 'Export'), ('delete', 'Delete'), ('integration_test', 'Integration Test'), ('settings_update', 'Settings Update'), ('account_security', 'Account Security')], db_index=True, max_length=32),
        ),
    ]
